import { Customer, CustomerLedgerEntry, Order, Payment, ActivityItem, UserProfile } from '@/types/ledger';

export const INITIAL_USER: UserProfile = {
  username: 'trconnect.org',
  name: 'TR Connect Admin',
  mobile: '01700000000',
  email: 'admin@trconnect.org',
  pin: '1234',
  createdAt: new Date().toISOString(),
};

export const INITIAL_CUSTOMERS: Customer[] = [
  { id: 'c_1', name: 'Md. Rafiqul Islam', mobile: '01812345678', createdAt: new Date(Date.now() - 86400000 * 5).toISOString() },
  { id: 'c_2', name: 'Kamal Hossain (Riyadh)', mobile: '01798765432', createdAt: new Date(Date.now() - 86400000 * 4).toISOString() },
  { id: 'c_3', name: 'Al-Amin Bhuiyan', mobile: '01911223344', createdAt: new Date(Date.now() - 86400000 * 3).toISOString() },
  { id: 'c_4', name: 'Tarequl Aziz', mobile: '01655443322', createdAt: new Date(Date.now() - 86400000 * 2).toISOString() },
  { id: 'c_5', name: 'Mizanur Rahman', mobile: '01511223344', createdAt: new Date(Date.now() - 86400000 * 1).toISOString() },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord_1',
    serial: 1,
    kind: 'personal',
    amount: 32000,
    customerId: 'c_1',
    customerName: 'Md. Rafiqul Islam',
    customerMobile: '01812345678',
    deliveryMethods: ['bkash'],
    recipientNumber: '01812345678',
    description: 'Family emergency support remittance - urgent bKash',
    emergency: true,
    riyal: { expected: 1000, received: 1000, description: 'Cash paid in Riyadh branch' },
    status: 'delivered',
    createdAt: new Date(Date.now() - 86400000 * 4).toISOString(),
    createdBy: 'trconnect.org',
    deliveredAt: new Date(Date.now() - 86400000 * 4 + 3600000).toISOString(),
    deliveredBy: 'trconnect.org',
    deliveryLast4: '8821',
    deliveryProof: null,
    deliveryDescription: 'Delivered to personal bKash wallet',
  },
  {
    id: 'ord_2',
    serial: 2,
    kind: 'agent',
    amount: 64000,
    customerId: 'c_2',
    customerName: 'Kamal Hossain (Riyadh)',
    customerMobile: '01798765432',
    deliveryMethods: ['nagad', 'bank'],
    recipientNumber: '01798765432',
    description: 'Shop merchandise payment to Dhaka wholesale agent',
    emergency: false,
    riyal: { expected: 2000, received: 1500, description: '500 SAR balance due next Sunday' },
    status: 'delivered',
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    createdBy: 'trconnect.org',
    deliveredAt: new Date(Date.now() - 86400000 * 3 + 7200000).toISOString(),
    deliveredBy: 'trconnect.org',
    deliveryLast4: '3341',
    deliveryProof: null,
    deliveryDescription: 'Bank transfer receipt confirmed',
  },
  {
    id: 'ord_3',
    serial: 3,
    kind: 'personal',
    amount: 16000,
    customerId: 'c_3',
    customerName: 'Al-Amin Bhuiyan',
    customerMobile: '01911223344',
    deliveryMethods: ['rocket'],
    recipientNumber: '01911223344',
    description: 'Household expenses transfer',
    emergency: true,
    riyal: { expected: 500, received: 500, description: 'Settled full' },
    status: 'new',
    createdAt: new Date(Date.now() - 3600000 * 3).toISOString(),
    createdBy: 'trconnect.org',
    deliveredAt: null,
    deliveredBy: null,
    deliveryLast4: null,
    deliveryProof: null,
    deliveryDescription: null,
  },
  {
    id: 'ord_4',
    serial: 4,
    kind: 'agent',
    amount: 48000,
    customerId: 'c_4',
    customerName: 'Tarequl Aziz',
    customerMobile: '01655443322',
    deliveryMethods: ['bkash', 'upay'],
    recipientNumber: '01655443322',
    description: 'Commercial consignment payout',
    emergency: false,
    riyal: { expected: 1500, received: 1000, description: '500 SAR due after arrival' },
    status: 'new',
    createdAt: new Date(Date.now() - 3600000 * 1).toISOString(),
    createdBy: 'trconnect.org',
    deliveredAt: null,
    deliveredBy: null,
    deliveryLast4: null,
    deliveryProof: null,
    deliveryDescription: null,
  },
];

export const INITIAL_LEDGER: CustomerLedgerEntry[] = [
  {
    id: 'led_1',
    customerId: 'c_1',
    orderId: 'ord_1',
    expected: 1000,
    received: 1000,
    description: 'Cash paid in Riyadh branch',
    createdAt: new Date(Date.now() - 86400000 * 4).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 4).toISOString(),
  },
  {
    id: 'led_2',
    customerId: 'c_2',
    orderId: 'ord_2',
    expected: 2000,
    received: 1500,
    description: '500 SAR balance due next Sunday',
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: 'led_3',
    customerId: 'c_3',
    orderId: 'ord_3',
    expected: 500,
    received: 500,
    description: 'Settled full',
    createdAt: new Date(Date.now() - 3600000 * 3).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 3).toISOString(),
  },
  {
    id: 'led_4',
    customerId: 'c_4',
    orderId: 'ord_4',
    expected: 1500,
    received: 1000,
    description: '500 SAR due after arrival',
    createdAt: new Date(Date.now() - 3600000 * 1).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 1).toISOString(),
  },
];

export const INITIAL_PAYMENTS: Payment[] = [
  {
    id: 'pay_1',
    amount: 50000,
    method: 'City Bank Ltd (Settlement)',
    description: 'Remittance pool payout via RTGS',
    proof: null,
    date: new Date(Date.now() - 86400000 * 2).toISOString(),
    addedBy: 'trconnect.org',
  },
  {
    id: 'pay_2',
    amount: 25000,
    method: 'bKash Merchant Pool',
    description: 'Direct agent account top-up',
    proof: null,
    date: new Date(Date.now() - 86400000 * 1).toISOString(),
    addedBy: 'trconnect.org',
  },
];

export const INITIAL_ACTIVITY: ActivityItem[] = [
  { id: 'act_1', text: 'Order TR-0001 delivered — ৳32,000', icon: 'delivery', createdAt: new Date(Date.now() - 86400000 * 4).toISOString() },
  { id: 'act_2', text: 'Order TR-0002 delivered — ৳64,000', icon: 'delivery', createdAt: new Date(Date.now() - 86400000 * 3).toISOString() },
  { id: 'act_3', text: 'Payment made — ৳50,000 via City Bank Ltd', icon: 'coin', createdAt: new Date(Date.now() - 86400000 * 2).toISOString() },
  { id: 'act_4', text: 'New order TR-0003 added — ৳16,000', icon: 'order', createdAt: new Date(Date.now() - 3600000 * 3).toISOString() },
  { id: 'act_5', text: 'New order TR-0004 added — ৳48,000', icon: 'order', createdAt: new Date(Date.now() - 3600000 * 1).toISOString() },
];
